### ISSUE TITLE
Scan Exif-/.txt-data setting enabled breaks Image Browser

### ISSUE THREAD

**Issue by SD-fan** [AlUlkesh/stable-diffusion-webui-images-browser#105]
I run Automatic1111 Commit hash: 22bcc7be428c94e9408f589966c2040187245d81 on Windows 10 and latest Firefox. 

If  Scan Exif-/.txt-data is enabled in the settings Image Browser breaks and I get this on the console

```
Traceback (most recent call last):
  File "C:\ML\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ML\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\ML\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ML\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ML\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ML\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\ML\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 756, in get_image_page
    filenames = get_all_images(img_path, sort_by, sort_order, keyword, tab_base_tag_box, img_path_depth, ranking_filter, aes_filter_min, aes_filter_max, exif_keyword, negative_prompt_search, use_regex, case_sensitive)
  File "C:\ML\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 632, in get_all_images
    cache_exif(fileinfos)
  File "C:\ML\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 385, in cache_exif
    (_, allExif, allExif_html) = modules.extras.run_pnginfo(image)
  File "C:\ML\stable-diffusion-webui\modules\extras.py", line 19, in run_pnginfo
    geninfo, items = images.read_info_from_image(image)
  File "C:\ML\stable-diffusion-webui\modules\images.py", line 620, in read_info_from_image
    exif = piexif.load(items["exif"])
  File "C:\ML\stable-diffusion-webui\venv\lib\site-packages\piexif\_load.py", line 28, in load
    exifReader = _ExifReader(input_data)
  File "C:\ML\stable-diffusion-webui\venv\lib\site-packages\piexif\_load.py", line 85, in __init__
    with open(data, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: b"b'Exif\\x00\\x00MM\\x00*\\x00\\x00\\x00\\x08\\x00\\x02\\x01\\x12\\x00\\x03\\x00\\x00\\x00\\x01\\x00\\x01\\x00\\x00\\x87i\\x00\\x04\\x00\\x00\\x00\\x01\\x00\\x00\\x00&\\x00\\x00\\x00\\x00\\x00\\x03\\xa0\\x01\\x00\\x03\\x00\\x00\\x00\\x01\\x00\\x01\\x00\\x00\\xa0\\x02\\x00\\x04\\x00\\x00\\x00\\x01\\x00\\x00\\x03W\\xa0\\x03\\x00\\x04\\x00\\x00\\x00\\x01\\x00\\x00\\x05\\x00\\x00\\x00\\x00\\x00'"
```

Image Browser has worked fine before. Seems to be an issue with latest Auto1111 version / Gradio version maybe.

**Comment by AlUlkesh** [comment]
I've seen this behaviour, when images have the incorrect extension. For example a file called ".png" is really a jpeg. Do you have a way to check that?

**Comment by SD-fan** [comment]
No sure what caused the prob. I reinstalld Image Browser, deleted all images. Now it works again. 
Maybe some broken image from a past generation?
If the issue pops up again, I'll let you know. You might want to close the issue.
Thanks for your quick response and the great work!
