### ISSUE TITLE
Img2Img and Extras tab of browser not working?

### ISSUE THREAD

**Issue by thunderbird89** [AlUlkesh/stable-diffusion-webui-images-browser#128]
Both tabs show an `Error` on all loading spinners, only the Txt2Img tab works.

Opening the _Extras_ tab:
```
Traceback (most recent call last):
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/zalanmeggyesi/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 800, in get_image_page
    filenames = get_all_images(img_path, sort_by, sort_order, keyword, tab_base_tag_box, img_path_depth, ranking_filter, aes_filter_min, aes_filter_max, exif_keyword, negative_prompt_search, use_regex, case_sensitive)
  File "/home/zalanmeggyesi/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 645, in get_all_images
    cache_exif(fileinfos)
  File "/home/zalanmeggyesi/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 398, in cache_exif
    (_, allExif, allExif_html) = modules.extras.run_pnginfo(image)
  File "/home/zalanmeggyesi/stable-diffusion-webui/modules/extras.py", line 19, in run_pnginfo
    geninfo, items = images.read_info_from_image(image)
  File "/home/zalanmeggyesi/stable-diffusion-webui/modules/images.py", line 620, in read_info_from_image
    exif = piexif.load(items["exif"])
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/piexif/_load.py", line 28, in load
    exifReader = _ExifReader(input_data)
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/piexif/_load.py", line 85, in __init__
    with open(data, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: b"b'Exif\\x00\\x00MM\\x00*\\x00\\x00\\x00\\x08\\x00\\x01\\x87i\\x00\\x04\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x1a\\x00\\x00\\x00\\x00\\x00\\x02\\xa0\\x02\\x00\\x04\\x00\\x00\\x00\\x01\\x00\\x00\\x02\\x00\\xa0\\x03\\x00\\x04\\x00\\x00\\x00\\x01\\x00\\x00\\x02\\x00\\x00\\x00\\x00\\x00'"
```

Opening _img2img_:
```
Traceback (most recent call last):
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/zalanmeggyesi/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/zalanmeggyesi/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 800, in get_image_page
    filenames = get_all_images(img_path, sort_by, sort_order, keyword, tab_base_tag_box, img_path_depth, ranking_filter, aes_filter_min, aes_filter_max, exif_keyword, negative_prompt_search, use_regex, case_sensitive)
  File "/home/zalanmeggyesi/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 645, in get_all_images
    cache_exif(fileinfos)
  File "/home/zalanmeggyesi/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/image_browser.py", line 420, in cache_exif
    wib_db.update_exif_data(conn, fi_info[0], allExif)
  File "/home/zalanmeggyesi/stable-diffusion-webui/extensions/stable-diffusion-webui-images-browser/scripts/wib/wib_db.py", line 191, in update_exif_data
    cursor.execute('''
sqlite3.OperationalError: database is locked
```

**Comment by AlUlkesh** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: b"b'Exif\\x00\\x00MM\\x00*\\x00\\x00\\x00\\x08\\x00\\x01\\x87i\\x00\\x04\\x00\\x00\\x00\\x01\\x00\\x00\\x00\\x1a\\x00\\x00\\x00\\x00\\x00\\x02\\xa0\\x02\\x00\\x04\\x00\\x00\\x00\\x01\\x00\\x00\\x02\\x00\\xa0\\x03\\x00\\x04\\x00\\x00\\x00\\x01\\x00\\x00\\x02\\x00\\x00\\x00\\x00\\x00'"`

When I've seen this before it was caused by misnamed images. Like a file with extension ".jpg", but which is really a png. Do you have a way to check this?

**Comment by thunderbird89** [comment]
@AlUlkesh Thanks for the pointer. Let me try and see if that's the case...

**Comment by thunderbird89** [comment]
Doesn't seem like it, I checked the entire output dir, but every file name matched its contents, as identified by ImageMagick's `identify` command...

**Comment by AlUlkesh** [comment]
I've just added a catch for that `FileNotFoundError`. Can you also enable warnings in `Settings-Image Browser-Print warning logs to the console`, so we can see which file is problematic?

**Comment by thunderbird89** [comment]
I updated the extension, and enabled logging to the console, so now I have a different exception:
```
Apr 09 18:53:57 unstable-diffusion-automatic webui.sh[5295]: db_version: 6
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]: Traceback (most recent call last):
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:   File "/path/to/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:     output = await app.get_blocks().process_api(
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:   File "/path/to/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1073, in process_api
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:     inputs = self.preprocess_data(fn_index, inputs, state)
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:   File "/path/to/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 962, in preprocess_data
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:     processed_input.append(block.preprocess(inputs[i]))
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]: IndexError: list index out of range
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]: Traceback (most recent call last):
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:   File "/path/to/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 394, in run_predict
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:     output = await app.get_blocks().process_api(
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:   File "/path/to/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1073, in process_api
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:     inputs = self.preprocess_data(fn_index, inputs, state)
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:   File "/path/to/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 962, in preprocess_data
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]:     processed_input.append(block.preprocess(inputs[i]))
Apr 09 18:55:40 unstable-diffusion-automatic webui.sh[5295]: IndexError: list index out of range
```

This is weird, because I didn't change the FS (aside from rendering more images, all PNGs)

**Comment by thunderbird89** [comment]
Huh. I did a _disable all extensions_, and that _fixed_ everything (but didn't disable anything...) and I can see the two files that are throwing:
```
kairaishi@unstable-diffusion-automatic:~$ identify /path/to/stable-diffusion-webui/outputs/extras-images/00016.png
/path/to/stable-diffusion-webui/outputs/extras-images/00016.png PNG 512x512 512x512+0+0 8-bit sRGB 366707B 0.000u 0:00.000
kairaishi@unstable-diffusion-automatic:~$ identify /path/to/stable-diffusion-webui/outputs/extras-images/00016.png
/path/to/stable-diffusion-webui/outputs/extras-images/00016.png PNG 512x512 512x512+0+0 8-bit sRGB 366707B 0.000u 0:00.000
```

**Comment by AlUlkesh** [comment]
This kinda looks like you were still accessing old info. Did you restart webui and open a new browser tab?

**Comment by thunderbird89** [comment]
I did, both. Now I did a complete server shutdown and restart, and it looks to be fixed.

Perhaps it really was a bad cache as you say?

**Comment by guansss** [comment]
I also ran into this problem, and the error is not `FileNotFoundError` but `OSError: [Errno 36] File name too long` because it's trying to read a file by `b"b'Exif\\x00\\x00...` which contains a very long exif. I ended up deleting all the problematic images and it's (temporarily?) fixed.

> When I've seen this before it was caused by misnamed images. Like a file with extension ".jpg", but which is really a png.

This is probably caused by webui producing broken exifs, refer to: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11126
