### ISSUE TITLE
NameError: name 'capture_level_value' is not defined

### ISSUE THREAD

**Issue by zyd232** [AlUlkesh/stable-diffusion-webui-images-browser#136]
The issue occurs after the update of f7c6ee41.
Fail to load the extension. Details:

```
Error loading script: image_browser.py
Traceback (most recent call last):
  File ".\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File ".\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File ".\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 177, in <module>
    if level_value >= capture_level_value:
NameError: name 'capture_level_value' is not defined
```

**Comment by MrKuenning** [comment]
Can confirm, working yesterday, today:

```
Error loading script: image_browser.py
Traceback (most recent call last):
  File "E:\AI\A1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\AI\A1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI\A1111\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 177, in <module>
    if level_value >= capture_level_value:
NameError: name 'capture_level_value' is not defined
```

**Comment by AlUlkesh** [comment]
Yeah, my bad. Please update and try again.

https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/57040c311fc540bca9ca9d5ada2a9dd521f03f95

**Comment by edisonchan** [comment]
It works after update.

**Comment by zyd232** [comment]
> Yeah, my bad. Please update and try again.
> 
> [57040c3](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/57040c311fc540bca9ca9d5ada2a9dd521f03f95)

Thank you, it works now.
