### ISSUE TITLE
console output error

### ISSUE THREAD

**Issue by bryanray** [AlUlkesh/stable-diffusion-webui-images-browser#157]
Error running install.py for extension Z:\z\sd\webui\extensions\stable-diffusion-webui-images-browser.
Command: "Z:\z\sd\system\python\python.exe" "Z:\z\sd\webui\extensions\stable-diffusion-webui-images-browser\install.py"
Error code: 1
stdout: Installing ImageReward requirement for image browser

stderr: Traceback (most recent call last):
  File "Z:\z\sd\webui\extensions\stable-diffusion-webui-images-browser\install.py", line 7, in <module>
    launch.run_pip("install image-reward", "ImageReward requirement for image browser")
  File "Z:\z\sd\webui\launch.py", line 128, in run_pip
    return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
  File "Z:\z\sd\webui\launch.py", line 96, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install ImageReward requirement for image browser.
Command: "Z:\z\sd\system\python\python.exe" -m pip install image-reward --prefer-binary
Error code: 2
stdout: Collecting image-reward
  Using cached image_reward-1.2-py3-none-any.whl (31 kB)
Collecting timm==0.6.13 (from image-reward)
  Using cached timm-0.6.13-py3-none-any.whl (549 kB)
Collecting transformers==4.27.4 (from image-reward)
  Using cached transformers-4.27.4-py3-none-any.whl (6.8 MB)
Collecting fairscale==0.4.13 (from image-reward)
  Using cached fairscale-0.4.13.tar.gz (266 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'

stderr: ERROR: Exception:
Traceback (most recent call last):
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "Z:\z\sd\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "Z:\z\sd\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
    super().__init__(
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 631, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "Z:\z\sd\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 692, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "Z:\z\sd\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "Z:\z\sd\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "Z:\z\sd\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\bryan\AppData\Local\Temp\pip-build-env-r99cw6wz\overlay\Lib\site-packages\setuptools\__init__.py", line 15, in <module>
    import setuptools.version
  File "C:\Users\bryan\AppData\Local\Temp\pip-build-env-r99cw6wz\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
    from ._importlib import metadata
  File "C:\Users\bryan\AppData\Local\Temp\pip-build-env-r99cw6wz\overlay\Lib\site-packages\setuptools\_importlib.py", line 44, in <module>
    import importlib.metadata as metadata  # noqa: F401
  File "importlib\metadata\__init__.py", line 17, in <module>
  File "importlib\metadata\_adapters.py", line 3, in <module>
  File "email\message.py", line 15, in <module>
  File "email\utils.py", line 29, in <module>
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'

**Comment by bryanray** [comment]
if once capture log level 4 is enable it will output this console error everytime it starts up.

even if turn off to level 0 none
![image](https://user-images.githubusercontent.com/1768531/236417779-65d22b7f-b9e8-4972-a468-27a3950b7204.png)

this error in console will still happen.

only way to remove this output in console when start up is to delete the extension.

**Comment by AlUlkesh** [comment]
It's trying to install a new requirement, but doesn't seem to be able to.

What happens if you do this manually in the webui directory:
```
venv\Scripts\activate.bat
pip install image-reward
```

**Comment by AlUlkesh** [comment]
You're on Windows, right?

Open your webui path in Windows Explorer:
![image](https://user-images.githubusercontent.com/99896447/236516544-75b078bb-abfa-4f69-aec7-6f7bc4b8fb47.png)

then overwrite the file location with `cmd` and press enter:
![image](https://user-images.githubusercontent.com/99896447/236516734-8ae26747-6dfa-473f-ba05-fd8c15cc28ea.png)

This should open a cmd-window in the right directory. There type in the venv and then the pip command:
![image](https://user-images.githubusercontent.com/99896447/236516983-990949e1-cc72-4fef-b9fa-9fe9c30fe71b.png)

**Comment by bryanray** [comment]
in fact i know this method :)) but i just click on python.exe and run that and it failed last time,

but using this method. it works, but why is that? what is the different between running python.exe vs in the folder cmd?

![image](https://user-images.githubusercontent.com/1768531/236518351-6a6fbc15-d473-4bbf-b713-75f3752bee2a.png)

**Comment by AlUlkesh** [comment]
If you click on python, a python shell should be opened. This shell interprets python code you enter.

But the venv and pip commands are not python code. They are code to support python. Small, but important difference.

**Comment by bryanray** [comment]
you are god :) thanks a lot!
i got lost half way, pardon my knowledge limitation

**Comment by AlUlkesh** [comment]
Yeah, I got off track today too...

I still don't know, why it didn't "just" work in the first place. Let's see if someone else also has that problem.

**Comment by Mtvrt123** [comment]
I had the same problem but I fixed it. The problem is AlUlkesh uses the cloned repo from a1111 what I see from the pictures. But I use the "https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.0.0-pre" the zipped version and the zipped version doesn't have the virtual environment (venv) / activate.bat. 

I know it uses the provided python folder but at the same time, it uses the libs from the local python310 folder. Maybe I don't know exactly.

What I did:
1. "pip install -r requirements.txt" in the sd-webui\webui folder / updated the requirements
2. then "pip install image-reward"

For the simple version, I reinstalled the requirements and installed image-reward in the appdata dir (local python310 install) and in the sd-webui dir from the zip and it works.

Which lib it uses I do not know I just shared my experience with the problem.

**Comment by momomomomomomo** [comment]
I also encountered the same problem, and after disabling the extension, there were no errors reported

Solved it according to the above method

**Comment by bryanray** [comment]
> I had the same problem but I fixed it. The problem is AlUlkesh uses the cloned repo from a1111 what I see from the pictures. But I use the "https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.0.0-pre" the zipped version and the zipped version doesn't have the virtual environment (venv) / activate.bat.

me too :) same here dude, i just cmd in the python path
