### ISSUE TITLE
Move to favorites not respecting `Add number to filename when saving` option

### ISSUE THREAD

**Issue by forsurefr** [AlUlkesh/stable-diffusion-webui-images-browser#196]
When clicking on move to favorites in the image browser it is not respecting the `Add number to filename when saving` option of SD web ui (`Saving images/grids` tab in the settings).
It will just move the image but not rename it to keep consistent numbers. I think it should try to increate the last number when doing it, like saving does in the web ui.

**Comment by AlUlkesh** [comment]
> I suggest that instead of trying to copy the file with manual corrections, `save_files()` from `modules/ui_common.py` is to be used. That way, this functionality will automatically be consistent with the behavior of saving images to favorites normally.

That's a great idea. I'll look into that.

**Comment by abel1502** [comment]
@AlUlkesh thanks! I'll check it tomorrow afternoon

**Comment by abel1502** [comment]
@AlUlkesh Weirdly, I don't think it has an effect... When I click "Copy to favorites", the file that appears in the output folder still has the same filename as before, and `log.csv` has no new entries... I'll look into what could be causing it. I have verified that I am indeed using the latest commit (203df93b).

**Comment by abel1502** [comment]
Yes, I have. I've also, after seeing the issue, clicked "Image Browser > Maintenance > Restart Debug" and then tried "Copy to Favorites" again, expecting to maybe see an error in the logs, but `image_browser.log` is completely empty. I'll try adding some manual `print`-based logging to see what is and isn't being called, then I'll report my findings

**Comment by abel1502** [comment]
Alright, here's the traceback:

```
Traceback (most recent call last):
  File "[redacted]\stable-diffusion-webui-forge\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 469, in save_image
    file_result, message_result = save_files(
  File "[redacted]\stable-diffusion-webui-forge\modules\ui_common.py", line 118, in save_files
    image = image_from_url_text(filedata)
  File "[redacted]\stable-diffusion-webui-forge\modules\infotext_utils.py", line 94, in image_from_url_text
    if filedata.startswith("data:image/png;base64,"):
AttributeError: 'tuple' object has no attribute 'startswith'
```

From this, I assume `images_data = [(image, None)]  # (image, info) tuple` is the wrong format, it seems to expect a URL instead.

**Comment by AlUlkesh** [comment]
Thanks, but before we're hunting phantoms... Which Webui are you actually using. The different forks do some things differently.

**Comment by AlUlkesh** [comment]
I have tested with Forge, that's not it.

The save_files function I think expects a tuple or a list, otherwise writing metadata to log.csv should not work. Does this work for you?

I just noticed this part in your trace:

```
  File "[redacted]\stable-diffusion-webui-forge\modules\ui_common.py", line 118, in save_files
    image = image_from_url_text(filedata)
```

Forge's current ui_common.py file does actually not contain this call, not at line 118, nor anywhere else:
https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/modules/ui_common.py#L118

Can you double-check, that you are running the current version of Forge?

**Comment by AlUlkesh** [comment]
Ah, yes, that does explain it. While Automatic1111 and Forge have the same ui_common implementation, ReForge differs from that.

Can you please check, if with your fix, metadata is written in log.csv? I suspect not.

**Comment by abel1502** [comment]
It is. This matches my expectations, considering `js_data` remains the same and the image bitmap is replaced by a base64 string of its contents

**Comment by AlUlkesh** [comment]
Ok, this version should support both. Thanks for your help!

**Comment by abel1502** [comment]
Great, thank you! I'll test this in a week, when I'm back home from a trip, and report if I find any issues

**Comment by abel1502** [comment]
Seems to work great for me, thanks!

**Comment by AlUlkesh** [comment]
Good to hear. Feel free to reopen the issue, if something comes up.
