### ISSUE TITLE
Crash on load - new install

### ISSUE THREAD

**Issue by thelittlemike** [AlUlkesh/stable-diffusion-webui-images-browser#201]
Not sure what the correct format is to post an issue but I just did a completely fresh install of A1111, then installed the Images Browser plugin. Did a Reload UI and then terminated and restarted A1111 and I'm getting the following messages in the console:

`Error loading script: image_browser.py
Traceback (most recent call last):
  File "C:\stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable_diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable_diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 105, in <module>
    check_image_browser_active_tabs()
  File "C:\stable_diffusion\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 95, in check_image_browser_active_tabs
    if last_default_tab[0] == "Others":
TypeError: 'NoneType' object is not subscriptable`

I really don't know where to continue from here. This extension is my go-to for every baseline install and always just worked.

**Comment by thelittlemike** [comment]
If it helps at all, I nuked my A1111 install again and instead of installing the extension via the UI, I installed previous commit 5795886bee895c2e69e5c64e67aa643da423511c and that is working just fine. So it was the June 4th or 5th merges that broke this.

**Comment by AlUlkesh** [comment]
Thanks. Can you check if the latest update fixes this?

**Comment by thelittlemike** [comment]
> Thanks. Can you check if the latest update fixes this?

That seems to have fixed it! I removed the folder from my extensions that I manually installed, ran the install from the UI, reloaded gradio, stopped/restarted in terminal and tab is still there and no errors in console. Thanks for the quick fix!

**Comment by AlUlkesh** [comment]
Great! Thanks.
