### ISSUE TITLE
Failed to load db file

### ISSUE THREAD

**Issue by vixenius** [AlUlkesh/stable-diffusion-webui-images-browser#238]
Log: *** Error executing callback ui_tabs_callback for D:\AINOVO\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py
    Traceback (most recent call last):
      File "D:\AINOVO\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "D:\AINOVO\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 1659, in on_ui_tabs
        create_tab(tab, current_gr_tab)
      File "D:\AINOVO\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 1109, in create_tab
        exif_cache = wib_db.load_exif_data(exif_cache)
      File "D:\AINOVO\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\wib\wib_db.py", line 705, in load_exif_data
        cursor.execute('''
    sqlite3.OperationalError: unable to open database file"

p.s. extension works good and loads images only first time when i reinstall it, and next time when i start the sd1111, i get the error and the tab wont load. the "wib.sqlite3" db file exists in "stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser", this started happening today. Help

**Comment by AlUlkesh** [comment]
Hmm, sounds like the db possibly got corrupted. Is your drive full perhaps?

First thing I would try is to move all wib*.* files in that directory to somewhere else. It will be recreated on the next run then.

**Comment by vixenius** [comment]
Hello again, I managed to fix it by reverting back to the pre-update backup config from yesterday (state to restore: both), now everything is working again. Before that i tried moving the db file, but it was not recreated, and no, my drive is not full. Thanks anyways. Cheers.

**Comment by AlUlkesh** [comment]
Glad to hear you got it working. If it should happen again, feel free to reopen the issue.
