### ISSUE TITLE
issue: database is locked

### ISSUE THREAD

**Issue by gsgoldma** [AlUlkesh/stable-diffusion-webui-images-browser#26]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 444, in get_image_page
    filenames = get_all_images(img_path, sort_by, sort_order, keyword, tabname_box, img_path_depth, ranking_filter, aes_filter, exif_keyword, negative_prompt_search)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 353, in get_all_images
    cache_exif(fileinfos)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 265, in cache_exif
    image = JpegImageFile(fi_info[0])
  File "D:\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFile.py", line 117, in __init__
    self._open()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\PIL\JpegImagePlugin.py", line 357, in _open
    raise SyntaxError(msg)
SyntaxError: not a JPEG file
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 444, in get_image_page
    filenames = get_all_images(img_path, sort_by, sort_order, keyword, tabname_box, img_path_depth, ranking_filter, aes_filter, exif_keyword, negative_prompt_search)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 353, in get_all_images
    cache_exif(fileinfos)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 270, in cache_exif
    wib_db.update_exif_data(conn, fi_info[0], allExif)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\wib\wib_db.py", line 143, in update_exif_data
    cursor.execute('''
sqlite3.OperationalError: database is locked

**Comment by AlUlkesh** [comment]
Do you perhaps have the database file `wib.sqlite3` open somewhere else, like a db browser, or a second instance of webui?

**Comment by EllangoK** [comment]
Idk if this how it happened for you, but this happened to me for the first time when I switched over to the db. So I loaded the `txt2img` and it had to build the cache for those images. While it was still loading, I switched to `img2img`, and that then presumably also called a build to the cache for that tab as that cache did not exist yet. Thus both were trying to write to the db at the same time.

**Comment by gsgoldma** [comment]
thanks!

**Comment by AlUlkesh** [comment]
>  While it was still loading, I switched to img2img, and that then presumably also called a build to the cache for that tab as that cache did not exist yet.

Oh, good catch. I wonder what the previous file-based implementation would have done in such a case. Corrupted file?

**Comment by AlUlkesh** [comment]
I increased the db default timeout for such cases from 5 to 30 seconds. Hopefully that makes it unlikely to run into this again.
