### ISSUE TITLE
processed_input.append(block.preprocess(inputs[i])) IndexError: list index out of range

### ISSUE THREAD

**Issue by PeterTemps** [AlUlkesh/stable-diffusion-webui-images-browser#36]
`cache_exif: 0/2443 cache_aes: 0/2443 0.0 seconds
Traceback (most recent call last):
  File "/home/piotr/VsCode/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/piotr/VsCode/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/piotr/VsCode/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
`

I also get some pip DB errors when i launch WebUI. I don't know if it's related to this extension?

`stderr:   Running command git clone --filter=blob:none --quiet https://github.com/NicolasBizzozzero/pattern /tmp/pip-install-hhbw76gc/pattern_ca2deaa566cd4d9cb4e5407a3d100287
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /bin/sh: 1: mysql_config: not found
      /bin/sh: 1: mariadb_config: not found
      /bin/sh: 1: mysql_config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hhbw76gc/mysqlclient_c69309e1436e4cfbb235c16cadee145a/setup.py", line 15, in <module>
          metadata, options = get_config()
        File "/tmp/pip-install-hhbw76gc/mysqlclient_c69309e1436e4cfbb235c16cadee145a/setup_posix.py", line 70, in get_config
          libs = mysql_config("libs")
        File "/tmp/pip-install-hhbw76gc/mysqlclient_c69309e1436e4cfbb235c16cadee145a/setup_posix.py", line 31, in mysql_config
          raise OSError("{} not found".format(_mysql_config_path))
      OSError: mysql_config not found
      mysql_config --version
      mariadb_config --version
      mysql_config --libs
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

`

**Comment by PeterTemps** [comment]
NEW UPDATE FIXED THE ERROR. Thanks!

**Comment by PeterTemps** [comment]
.

**Comment by AlUlkesh** [comment]
Latest commit seems to have solved the issue. I'll close this. If anyone still has problems, please make a new issue.
