### ISSUE TITLE
Error reading a test png file

### ISSUE THREAD

**Issue by sidcarton1587** [AlUlkesh/stable-diffusion-webui-images-browser#54]
This is probably some sort of configuration error but on a fresh install when I go to the Images Browser tab and try to select "First Page" on any of the tabs I get the stacktrace below. I'm not sure why it's trying to read the gradio test images in the venv directory, but the last image where it throws an error trying to read a PNG file, namely .\venv\Lib\site-packages\gradio\test_data\test_image.png** appears to be accurate, since the image file looks like it's actually a GIF:

```
$ file venv/Lib/site-packages/gradio/test_data/test_image.png
venv/Lib/site-packages/gradio/test_data/test_image.png: GIF image data, version 89a, 61 x 68
```

The gradio version is 3.16.2

The stacktrace is here:
```

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\ghirp\Development\test\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 547, in get_image_page
    filenames = get_all_images(img_path, sort_by, sort_order, keyword, tab_base_tag_box, img_path_depth, ranking_filter, aes_filter, exif_keyword, negative_prompt_search)
  File "D:\ghirp\Development\test\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 456, in get_all_images
    cache_exif(fileinfos)
  File "D:\ghirp\Development\test\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 342, in cache_exif
    image = PngImageFile(fi_info[0])
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFile.py", line 117, in __init__
    self._open()
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\PIL\PngImagePlugin.py", line 732, in _open
    raise SyntaxError(msg)
SyntaxError: not a PNG file
```

**Comment by AlUlkesh** [comment]
I just made a fresh install and tried it out. But there were no issues here.

Can you update the extension to the latest version and set the debugging option? (Settings - Image Browser - Print debug logs to the console)

Then restart webui and run to the error again and post the console log.

**Comment by sidcarton1587** [comment]
Okay did a fresh install and added the debug logging. Here are the results:

...
No EXIF in image or txt file for .\screenshot.png
No EXIF in image or txt file for .\screenshot.png
No EXIF in image or txt file for .\test\test_files\img2img_basic.png
No EXIF in image or txt file for .\test\test_files\img2img_basic.png
No EXIF in image or txt file for .\test\test_files\mask_basic.png
No EXIF in image or txt file for .\test\test_files\mask_basic.png
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\templates\cdn\favicon.png
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\templates\cdn\favicon.png
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\templates\frontend\favicon.png
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\templates\frontend\favicon.png
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\test_data\cheetah1-copy.jpg
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\test_data\cheetah1-copy.jpg
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\test_data\cheetah1.jpg
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\test_data\cheetah1.jpg
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\test_data\cheetah2.jpg
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\test_data\cheetah2.jpg
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\test_data\lion.jpg
No EXIF in image or txt file for .\venv\Lib\site-packages\gradio\test_data\lion.jpg
Traceback (most recent call last):
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\ghirp\Development\test\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 553, in get_image_page
    filenames = get_all_images(img_path, sort_by, sort_order, keyword, tab_base_tag_box, img_path_depth, ranking_filter, aes_filter, exif_keyword, negative_prompt_search)
  File "D:\ghirp\Development\test\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 462, in get_all_images
    cache_exif(fileinfos)
  File "D:\ghirp\Development\test\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 348, in cache_exif
    image = PngImageFile(fi_info[0])
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFile.py", line 117, in __init__
    self._open()
  File "D:\ghirp\Development\test\stable-diffusion-webui\venv\lib\site-packages\PIL\PngImagePlugin.py", line 732, in _open
    raise SyntaxError(msg)
SyntaxError: not a PNG file

**Comment by AlUlkesh** [comment]
Unfortunately the important info is missing. I need what comes before what you posted. At least starting with:
```
z:\AI\tests\stable-diffusion-webui_20230226\venv\Scripts\python.exe 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Windows 10.0.19044
0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

Gradio 3.16.2
Z:\AI\tests\stable-diffusion-webui_20230226
...
```

**Comment by sidcarton1587** [comment]
Here is the attached console log.

[console.log](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/files/10834189/console.log)

**Comment by AlUlkesh** [comment]
Ok, it's because of this:
![image](https://user-images.githubusercontent.com/99896447/221424882-6e468cc7-6c19-4c02-93cf-91aeb75ed0c5.png)

You apparently are using the first option and leaving the others empty. You must be the first person using this extension who does this :laughing:

I'll try to put a fix in. What do you expect to happen? All image browser tabs showing the same thing?

**Comment by sidcarton1587** [comment]
Well the odd thing is that SD writes by datestamp, so even if I set the above directories to their original values the image browser still doesn't pick them up. 

```
Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.62it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.16it/s]
curr_path: outputs\txt2img-images
cache_exif: 0/0 cache_aes: 0/0 0.0 seconds
```

And looking outputs, I see this:

```
$ ls -R outputs/
outputs/:
2023-02-26/  img2img-grids/   txt2img-grids/
extras/      img2img-images/  txt2img-images/

outputs/2023-02-26:
00000-2403993945.png  00000-2403993945.txt

outputs/extras:

outputs/img2img-grids:

outputs/img2img-images:

outputs/txt2img-grids:

outputs/txt2img-images:

ghirp@NEPTUNE MINGW64 /d/ghirp/Development/test/stable-diffusion-webui (master)
```

As far I can tell my SD is up-to-date, but maybe need a complete reinstall?

**Comment by AlUlkesh** [comment]
Did you stop and restart webui after chaning the values?

**Comment by sidcarton1587** [comment]
Yep. Multiple times.

**Comment by AlUlkesh** [comment]
When you look in config.json what do you see here now:

    "outdir_samples": "",
    "outdir_txt2img_samples": "outputs/txt2img-images",
    "outdir_img2img_samples": "outputs/img2img-images",
    "outdir_extras_samples": "outputs/extras-images",
    "outdir_grids": "",
    "outdir_txt2img_grids": "outputs/txt2img-grids",
    "outdir_img2img_grids": "outputs/img2img-grids",
    "outdir_save": "log/images",

**Comment by sidcarton1587** [comment]
```
  "outdir_samples": "outputs",
    "outdir_txt2img_samples": "outputs/txt2img-images",
    "outdir_img2img_samples": "outputs/img2img-images",
    "outdir_extras_samples": "outputs/extras-images",
    "outdir_grids": "outputs",
    "outdir_txt2img_grids": "outputs/txt2img-grids",
    "outdir_img2img_grids": "outputs/img2img-grids",
    "outdir_save": "log/images",
```

**Comment by sidcarton1587** [comment]
Okay, so I set the outdir_samples and outdir_grids to blank (""), then it works.

**Comment by AlUlkesh** [comment]
Ok, the latest commit should be able to handle both versions:
```
    "txt2img": opts.outdir_samples or opts.outdir_txt2img_samples,
    "img2img": opts.outdir_samples or opts.outdir_img2img_samples,
    "txt2img-grids": opts.outdir_grids or opts.outdir_txt2img_grids,
    "img2img-grids": opts.outdir_grids or opts.outdir_img2img_grids,
    "Extras": opts.outdir_samples or opts.outdir_extras_samples,

```
