### ISSUE TITLE
UNIQUE constraint failed

### ISSUE THREAD

**Issue by AlUlkesh** [AlUlkesh/stable-diffusion-webui-images-browser#63]
```
Image Browser: Upgrading database from version 1 to version 3
Error executing callback ui_tabs_callback for E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py
Traceback (most recent call last):
  File "E:\AI\Automatic1111\stable-diffusion-webui\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 1030, in on_ui_tabs
    create_tab(tab, current_gr_tab)
  File "E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 725, in create_tab
    db_version = wib_db.check()
  File "E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\wib\wib_db.py", line 339, in check
    migrate_path_recorder_dirs(cursor)
  File "E:\AI\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\wib\wib_db.py", line 246, in migrate_path_recorder_dirs
    cursor.execute('''
```

**Comment by AlUlkesh** [comment]
@ouoertheo:
I found it, can you try the latest commit?

**Comment by ouoertheo** [comment]
Ah, I actually ran sd in debug and rooted out the duplicate entry, then deleted it from the table using the debug console and this command
```
 cursor.execute('''
 DELETE FROM path_recorder
 WHERE path = 'E:\\AI\\Automatic1111\\stable-diffusion-webui\\outputs\\characters'
 ''')
 ```
No more error.
Sorry, won't have a chance to see if that new code check fixed it :-/

**Comment by AlUlkesh** [comment]
Ah, well, it should prevent others to run into this then.
