### ISSUE TITLE
Error when using "Others" tab option with external folders

### ISSUE THREAD

**Issue by Aamir3d** [AlUlkesh/stable-diffusion-webui-images-browser#64]
Process followed
1. Add new directories to the "Others" tab
2. Click the directory in the dropdown
3. Click "First Page"
Expected behavior : Images should be seen
Current behavior : Error shows, and if the UI is reloaded, the image browser tab vanishes from the Automatic1111 UI.
Restarting the webui-user.bat file restores the image browser tab.

Screenshot:
![image](https://user-images.githubusercontent.com/122131887/222987710-6b0d5717-8caf-4e5a-a5e5-1e96b1411c18.png)

```
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "O:\automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 590, in get_image_page
    filenames = get_all_images(img_path, sort_by, sort_order, keyword, tab_base_tag_box, img_path_depth, ranking_filter, aes_filter, exif_keyword, negative_prompt_search)
  File "O:\automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 499, in get_all_images
    cache_exif(fileinfos)
  File "O:\automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 357, in cache_exif
    image = PngImageFile(fi_info[0])
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\PIL\ImageFile.py", line 117, in __init__
    self._open()
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\PIL\PngImagePlugin.py", line 732, in _open
    raise SyntaxError(msg)
SyntaxError: not a PNG file

```

Additional info:
This could possibly be happening because there are .log or .txt files within the InvokeAI output folder

**Comment by AlUlkesh** [comment]
That sounds more like you have a file with a ".png" extension in there, that is not really a png-file.

But the Image Browser shouldn't break because of that, I'll put a fix in for that.

**Comment by Aamir3d** [comment]
> That sounds more like you have a file with a ".png" extension in there, that is not really a png-file.
> 
> But the Image Browser shouldn't break because of that, I'll put a fix in for that.

Thanks for the quick reply!
I usually render to JPG to save on disk space. 
I can check with Irfanview and see if there's any mislabeled PNG or JPG with an incorrect extension.

Great extension btw - makes A1111 much more usable.

**Comment by AlUlkesh** [comment]
Thanks.

This should fix that. I'll probably have to do another pass, since this now leaves empty image thumbnails in the gallery, but this should get you going.

**Comment by Aamir3d** [comment]
> Thanks.
> 
> This should fix that. I'll probably have to do another pass, since this now leaves empty image thumbnails in the gallery, but this should get you going.

It works now, thank you!
Appreciate the effort you put into this.

**Comment by Aamir3d** [comment]
We can close this @AlUlkesh ? Unless you're updating something else in relation to this issue.

**Comment by AlUlkesh** [comment]
Yeah, when I get around to it, I want to see if I can do something about the empty image thumbnail. Let's leave it open for now.
