### ISSUE TITLE
Image browser sending wrong image to img2img

### ISSUE THREAD

**Issue by Aamir3d** [AlUlkesh/stable-diffusion-webui-images-browser#78]
Workflow:
I deleted a few files in the image browser text2img tab
Deletion was manual, using the 'delete' key on the keyboard, and navigating with arrow key right

After deleting, found 1 good image.
To enlarge this image, I sent it to img2img, but for some reason, the wrong image is being sent to the img2img tab.

Debug code
```
Deleting file O:\automatic1111\stable-diffusion-webui\outputs\txt2img-images\02632-889059784-1boy, very sharp portrait,harrison ford as Indiana jones, fedora hat, (six gun_1.2), black hair, khaki jungle shirt, brown leath.jpg
Traceback (most recent call last):
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "O:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "O:\automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-images-browser\scripts\image_browser.py", line 285, in delete_image
    index = list(filenames).index(name)
ValueError: 'O:\\automatic1111\\stable-diffusion-webui\\outputs\\txt2img-images\\02632-889059784-1boy, very sharp portrait,harrison ford as Indiana jones, fedora hat, (six gun_1.2), black hair, khaki jungle shirt, brown leath.jpg' is not in list
Deleting file O:\automatic1111\stable-diffusion-webui\outputs\txt2img-images\02629-889059781-1boy, very sharp portrait,harrison ford as Indiana jones, fedora hat, (six gun_1.2), black hair, khaki jungle shirt, brown leath.jpg
Deleting file O:\automatic1111\stable-diffusion-webui\outputs\txt2img-images\02628-889059780-1boy, very sharp portrait,harrison ford as Indiana jones, fedora hat, (six gun_1.2), black hair, khaki jungle shirt, brown leath.jpg
Deleting file O:\automatic1111\stable-diffusion-webui\outputs\txt2img-images\02625-30983308-1boy, very sharp portrait,harrison ford as Indiana jones, fedora hat, (six gun_1.2), black hair, khaki jungle shirt, brown leath.jpg
Deleting file O:\automatic1111\stable-diffusion-webui\outputs\txt2img-images\02622-4139493715-1boy, very sharp portrait,harrison ford as Indiana jones, fedora hat, (six gun_1.2), black hair, khaki jungle shirt, brown leath.jpg
Deleting file O:\automatic1111\stable-diffusion-webui\outputs\txt2img-images\02630-889059782-1boy, very sharp portrait,harrison ford as Indiana jones, fedora hat, (six gun_1.2), black hair, khaki jungle shirt, brown leath.jpg
Deleting file O:\automatic1111\stable-diffusion-webui\outputs\txt2img-images\02627-889059779-1boy, very sharp portrait,harrison ford as Indiana jones, fedora hat, (six gun_1.2), black hair, khaki jungle shirt, brown leath.jpg
```

Screenshot
![image](https://user-images.githubusercontent.com/122131887/224025383-084db68a-63e4-48b9-a8f4-375beedbc136.png)

IMG2IMG tab:
![image](https://user-images.githubusercontent.com/122131887/224025534-b632dfb4-2021-440e-b322-43fa95e287f7.png)

**Comment by AlUlkesh** [comment]
I think this happened to me once also, but at that point I wasn't able to reproduce it.
